### ISSUE TITLE
missing glyphs

### ISSUE THREAD

**Issue by cjdunn** [TypeNetwork/Ruda-new#1]
Ruda, glyphs to add (from bakery report):
0x00A0 nbspace, 0x000D (CARRIAGE RETURN), 0x00A0 (NO-BREAK SPACE), 0x2026 (HORIZONTAL ELLIPSIS), 0x2044 (FRACTION SLASH), 0x2074 (SUPERSCRIPT FOUR) and 0x2215 (DIVISION SLASH)

**Comment by victoriaalissia** [comment]
Thanks, added in fea-ufo-conv

**Comment by cjdunn** [comment]
@victoriaalissia thanks! I've pulled your changes into the latest branch, which is [fea-update-build](https://github.com/marmonsalve/Ruda-new/compare/master...TypeNetwork:fea-update-build?expand=1) (and miraculously there was no conflict 🎉)

**Comment by cjdunn** [comment]
Oh wait never mind, the UFOs are not in the same folder. So I'll need to copy in the new glyphs now and delete the duplicate UFOs

**Comment by cjdunn** [comment]
Fixed with this PR: 
https://github.com/TypeNetwork/Ruda-new/pull/2
