### ISSUE TITLE
Mathematical signs are misaligned

### ISSUE THREAD

**Issue by thlinard** [TypeNetwork/Ruda-new#19]
The horizontal bar of + − ÷ should be the same, and aligned vertically (in the middle) with × =.

<img width="1049" alt="Ruda" src="https://user-images.githubusercontent.com/13808824/91024818-c819b700-e5f8-11ea-85ee-fd95144e8176.png">

**Comment by thlinard** [comment]
More complete specimen (1×<>+÷−¬=≠±3):

<img width="1599" alt="Ruda" src="https://user-images.githubusercontent.com/13808824/91158226-9f5ff300-e6c6-11ea-9be6-c2ccaa153353.png">

**Comment by pichotta** [comment]
This is a foundry related design decision. 
See https://github.com/marmonsalve/Ruda-new/issues/new
