### ISSUE TITLE
Accent Positioning  /dcircumflexbelow    /dotbelow

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/Ruda-new#4]
@richardlipton coordinate with @cjdunn re: branch and fix for

/dcircumflexbelow
shifting postion from Regular to Black

/dotbelow
shifting position across weight
see it in the A with dots and 
check in other glyphs that contain dot below
Abrevedotbelow Acircumflexdotbelow Adotbelow

after [wght].ttf is generated check it in use in a tool like  typetools.typenetwork or videoproof.typenetwork

![:circumbelow :dotbelow](https://user-images.githubusercontent.com/6576107/68826274-304f6b80-066b-11ea-8abc-c1e9179f14dd.png)

**Comment by pichotta** [comment]
@richardlipton @cjdunn 
while investigating these accents could you indicate if and when a component is referencing another component (instead of an outline)?

we are wondering if there is something can be resolved at the fontmake level

**Comment by richardlipton** [comment]
@cjdunn @pichotta 
I did notice this accent movement issue in Typetools and Videoproof. I can’t figure out why it is happening. It isn’t apparent that a component is referencing another component (instead of an outline).

**Comment by cjdunn** [comment]
I've looked into this more and found what I think is the issue. There's a negative transformation on some components in the Black master only (aka components are flipped) for these glyphs:
Acircumflexdotbelow Adotbelow Ecircumflexdotbelow Edotbelow Ocircumflexdotbelow Odotbelow Udotbelow Uhorndotbelow Ydotbelow dcircumflexbelow

so basically the /dotbelow and /circumflex is flipped for these and needs to be un-flipped and re-positioned 

BTW Victoria is making some other updates for Ruda so I've asked her to fix these as well

**Comment by victoriaalissia** [comment]
Done! Syncing shortly.

**Comment by cjdunn** [comment]
Looks good, the issue is fixed here: https://github.com/TypeNetwork/Ruda-new/commit/c2aa3aaecf732f3cd638e907be9c010bcd939c03
