### ISSUE TITLE
Outlines:  ia-cy

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/Ruda-new#5]
@richardlipton coordinate with @cjdunn re: branch 
and fix for switchback outlines used in /ia-cy that is resulting in white artifacts

![:ia-cy](https://user-images.githubusercontent.com/6576107/68826399-c4213780-066b-11ea-89dc-46bbdfbab95c.png)

![:ia-cy artifacts](https://user-images.githubusercontent.com/6576107/68826460-064a7900-066c-11ea-8932-86dde215cc52.png)

**Comment by richardlipton** [comment]
Fixed
