### ISSUE TITLE
Outlines:  /hungarumlautcomb.case

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/Ruda-new#6]
@richardlipton coordinate with @cjdunn re: branch and fix for:

one of the /hungarumlauts has an interpolation error in masters

![:hungarumlaut](https://user-images.githubusercontent.com/6576107/68826524-4f023200-066c-11ea-865d-673d3e2f6614.png)

**Comment by richardlipton** [comment]
Fixed
